# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
vector10=np.empty(10)
print(vector10)

[ 0.00000000e+000 -1.24958287e-310  0.00000000e+000  0.00000000e+000
  0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
  0.00000000e+000  0.00000000e+000]


3. Create a vector with values ranging from 10 to 49

In [7]:
vector10To49=np.array(range(10))

4. Find the shape of previous array in question 3

In [4]:
print("Size of the array:", vector10To49.size)

Size of the array: 10


5. Print the type of the previous array in question 3

In [5]:
print(vector10To49)

[0 1 2 3 4 5 6 7 8 9]


6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_confing())

1.18.5


AttributeError: module 'numpy' has no attribute 'show_confing'

7. Print the dimension of the array in question 3


In [8]:
print(vector10To49.ndim)

1


8. Create a boolean array with all the True values

In [9]:
boolArray=np.ones((1,5), dtype=bool)

9. Create a two dimensional array




In [10]:
My2DArray=np.random.randn(3,4)

10. Create a three dimensional array



In [11]:
My3DArray=np.random.randn(3,4,6)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [ ]:
d=np.array([1,2,3,4,5,6])
print(d.flip())

12. Create a null vector of size 10 but the fifth value which is 1 

In [ ]:
NArray=np.enmpty(10)
NArray[4]=1

13. Create a 3x3 identity matrix

In [ ]:
Identity3d=np.identity(3)
print(Identity3d)

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [12]:
arr = np.array([1,2,3,4,5], dtype=float)
print(arr)


[1. 2. 3. 4. 5.]


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [13]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr1*arr2)

[[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [14]:
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
print(arr2-arr1)

[[-1.  2. -2.]
 [ 3. -3.  6.]]


17. Extract all odd numbers from arr with values(0-9)

In [15]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    print(NumArray[i])

[0 1 2 3 4 5 6 7 8 9]
1
3
5
7
9


18. Replace all odd numbers to -1 from previous array

In [16]:
NumArray=np.arange(10)
print(NumArray)
for i in range(10):
  if(NumArray[i]%2!=0):
    NumArray[i]=-1
print(NumArray)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [17]:
arr = np.arange(10)
arr[5]=arr[6]=arr[7]=arr[8]=12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


20. Create a 2d array with 1 on the border and 0 inside

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [18]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(np.where(arr2d==5, 12, arr2d))

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [19]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(np.where(arr3d>=0, 64, arr3d))

[[[64 64 64]
  [64 64 64]]

 [[64 64 64]
  [64 64 64]]]


23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [20]:
Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
FirstRow=(Array2D[0,:3 ])
print(FirstRow)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [21]:

Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
Second2nd=(Array2D[1,1])
print(Second2nd)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [22]:

Array2D=np.arange(0,9,1).reshape(3,3)
print(Array2D)
ThridCol2Val=(Array2D[0:2, 2])
print(ThridCol2Val)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[2 5]


26. Create a 10x10 array with random values and find the minimum and maximum values

In [23]:
Ten10Arr = np.random.randint(100, size=(10, 10))
print(Ten10Arr)
print(np.min(Ten10Arr))
print(np.max(Ten10Arr))

[[ 6 74 53 14 69  5 38 89 29 41]
 [91 71 62 45 61 26 29 62 15 75]
 [50 93 20 89 41 83 76 68  9 26]
 [26 37 91 83 97 45 55 70 31 80]
 [70 20 13 77 67 96 92 92 12 69]
 [72 95 67 76 77 63 92  9 29 61]
 [11 13 71 77 17 61 91 50 80 60]
 [32 62 57 89 75 42 24 70 63 32]
 [ 4 37 70 32 86 76 98 64 99 26]
 [65 85 69 46 42 74 13 13 89  8]]
4
99


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [24]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print([key for key, val in enumerate(a) if val in set(b)])

[1, 3, 5, 7]


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [26]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Indeces where name is not Will : ", np.where(names!="Will"))

print("Values : ",names[np.where(names!="Will")])

Indeces where name is not Will :  (array([0, 1, 3, 5, 6], dtype=int64),)
Values :  ['Bob' 'Joe' 'Bob' 'Joe' 'Joe']


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [27]:
names2 = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(data)

mask=(names2!="Will")&(names2!="Joe")
data[mask]

[[ 0.71768136 -1.73724634  2.31684132 -0.90779875]
 [ 0.73181531  0.72732985  0.3885117  -0.38145051]
 [ 0.08273531 -1.96648514 -0.77740331  0.63598733]
 [ 1.07719047  0.22359333  0.11524424  0.38227459]
 [-0.22198956 -0.19365717 -0.22335796  0.56598766]
 [ 1.22628412 -0.3129462  -0.49883887 -0.53763124]
 [-0.3858926  -0.63473718  0.98027045 -0.4677657 ]]


array([[ 0.71768136, -1.73724634,  2.31684132, -0.90779875],
       [ 1.07719047,  0.22359333,  0.11524424,  0.38227459]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [28]:
TwoDArray = np.array(range(1,16), dtype=np.float64).reshape(5,3)
print(TwoDArray)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [29]:
ThreeDArray = np.array(range(1,17), dtype=np.float64).reshape(2,2,4)
print(ThreeDArray)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]]

 [[ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]]


33. Swap axes of the array you created in Question 32

In [30]:
ThreeDArray.reshape(4,2,2)

array([[[ 1.,  2.],
        [ 3.,  4.]],

       [[ 5.,  6.],
        [ 7.,  8.]],

       [[ 9., 10.],
        [11., 12.]],

       [[13., 14.],
        [15., 16.]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [31]:
SQARTArray = np.sqrt(abs(np.random.randn(10)))
print(SQARTArray)
RemoveingLessThanHalf=np.where(SQARTArray<0.5,0,SQARTArray)
print(RemoveingLessThanHalf)

[0.9801937  0.31741713 0.74832553 0.66879436 0.56977015 0.74069311
 0.55254983 0.42199263 0.91784903 0.26501563]
[0.9801937  0.         0.74832553 0.66879436 0.56977015 0.74069311
 0.55254983 0.         0.91784903 0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [32]:
RandomArray1=np.random.randint(12, size=(1, 12))[0]
RandomArray2=np.random.randint(12, size=(1, 12))[0]
MaxArr=np.maximum(RandomArray1,RandomArray2)

print("Array1 :",RandomArray1)
print("Array2 :",RandomArray2)
print("Maximum of two:", MaxArr)

Array1 : [ 1 11  8  5  5  5  1  7  8 11  5  7]
Array2 : [ 6 11  2 10  9  9  6  2  8  1  8  6]
Maximum of two: [ 6 11  8 10  9  9  6  7  8 11  8  7]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
print(np.sort(np.unique(names)))

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [34]:
from collections import Counter

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

ca = Counter(a)
cb = Counter(b)

result_a = sorted((ca - cb).elements())

print(result_a)

[1, 2, 3, 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [35]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
for i in range(3):
  sampleArray[i,1]=newColumn[0,i]

print(sampleArray)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [36]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z=x.reshape(1,6)*y.reshape(1,6)
print(z)

[[ 6. 46. -3. 28. 40. 54.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [37]:
Arr20 = np.random.randint(20, size=(5, 4))
print(Arr20)
print("Sum of All Numbers : ",np.sum(Arr20))

[[15 19  4 14]
 [ 6 13 14 14]
 [11 13  1  9]
 [10  0 13  6]
 [ 5 10 12 17]]
Sum of All Numbers :  206
