# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [1]:
import numpy as np
Arr1D=np.arange(10)
Arr2D=Arr1D.reshape(2,5)

print(Arr1D)
print()
print(Arr2D)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [2]:
arr1=np.arange(10).reshape(2,5)
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
arr3=np.vstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [3]:

arr1=np.arange(10).reshape(2,5)
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
arr3=np.hstack((arr1,arr2))
arr3

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [4]:
arr1=np.arange(10).reshape(2,5)
np.ravel(arr1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [5]:
arr10=np.arange(15).reshape(3,5)
np.ravel(arr10)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [6]:
arr1D=np.arange(15)
arr1D
arr1D.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [7]:
arr5b5=np.random.randint(200,size=25).reshape(5,5)
np.sqrt(arr5b5)

array([[ 5.38516481,  2.64575131,  8.48528137, 12.489996  , 11.70469991],
       [11.22497216,  4.12310563, 12.76714533,  6.        , 12.12435565],
       [13.82027496,  7.14142843, 10.95445115, 13.74772708, 12.32882801],
       [ 9.48683298, 11.61895004, 13.6381817 , 10.95445115, 10.77032961],
       [12.84523258,  9.59166305,  6.78232998,  6.92820323,  8.06225775]])

## Question:8

### Create 5x6 an array and find the mean?

In [8]:
arr5b6=np.random.randint(200,size=30).reshape(5,6)
print(arr5b6)
np.mean(arr5b6)

[[194  95 141  14  90  71]
 [ 89 184 181  50 158  52]
 [122  66 118 148   5 124]
 [ 38 120  37  87 110  72]
 [102 172  45 198 111 175]]


105.63333333333334

## Question:9

### Find the standard deviation of the previous array in Q8?

In [9]:
np.std(arr5b6)

53.70628972062356

## Question:10

### Find the median of the previous array in Q8?

In [10]:
np.median(arr5b6)

106.0

## Question:11

### Find the transpose of the previous array in Q8?

In [11]:
np.transpose(arr5b6)

array([[194,  89, 122,  38, 102],
       [ 95, 184,  66, 120, 172],
       [141, 181, 118,  37,  45],
       [ 14,  50, 148,  87, 198],
       [ 90, 158,   5, 110, 111],
       [ 71,  52, 124,  72, 175]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [12]:
arr4b4=np.random.randint(200,size=16).reshape(4,4)
print(arr4b4)
trace = np.trace(arr4b4)
print(trace)

[[171 198 177 130]
 [128  58 193 150]
 [119  98  55  92]
 [111 152 171 117]]
401


## Question:13

### Find the determinant of the previous array in Q12?

In [13]:
np.linalg.det(arr4b4)

43729836.00000005

## Question:14

### Find the 5th and 95th percentile of an array?

In [14]:
print(np.percentile(arr4b4, 5))

print(np.percentile(arr4b4, 95))

57.25
194.25


## Question:15

### How to find if a given array has any null values?

In [15]:
an_array = np.empty((3,3))

an_array[:] = np.NaN

print(np.isnan(an_array))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
